# Generated by Django 5.1.1 on 2024-10-15 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categories',
            table='category',
        ),
    ]
