# Generated by Django 5.1.1 on 2024-10-16 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods_app', '0005_alter_products_discount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('id',), 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
